ALTER TABLE "Clinic"
ADD COLUMN "smsCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "aiRequestCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "smsMonthlyLimit" INTEGER NOT NULL DEFAULT 500,
ADD COLUMN "aiMonthlyLimit" INTEGER NOT NULL DEFAULT 1000;

ALTER TABLE "Clinic" DROP COLUMN IF EXISTS "apiKeys";
