FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-client

COPY backend/package*.json ./
RUN npm ci

COPY backend/prisma ./prisma/
RUN npx prisma generate

COPY backend/ .

EXPOSE 4000

CMD ["node", "index.js"]